version: '2'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
    command: --logging=debug --addr=0.0.0.0
  redis:
    image: redis:latest
  mongo:
    image: mongo:latest
